name: Flutter CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5
      - name: Unit test
        run: flutter test --coverage
      - name: Upload coverage to artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/lcov.info
